/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import model.bean.Entidades;
import model.bean.Funcionarios;
import model.dao.EntidadesDAO;
import model.dao.FuncionariosDAO;

/**
 *
 * @author Senai
 */
public class TelaTarefa extends javax.swing.JFrame {

    Entidades bean = new Entidades();
    EntidadesDAO dao = new EntidadesDAO();

    public TelaTarefa() {
        initComponents();
        ReadJtable();
        setComboBox();

        tarefasTabela.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent event) {
                if (!event.getValueIsAdjusting()) {
                    int linhaselecionada = tarefasTabela.getSelectedRow();
                    if (linhaselecionada != -1) {
                        int IdAtual = (int) tarefasTabela.getValueAt(linhaselecionada, 0);
                        bean.setIdentidades(IdAtual);
                    }
                }
            }

        });
    }

    public void ReadJtable() {
        DefaultTableModel modelo = (DefaultTableModel) tarefasTabela.getModel();
        modelo.setNumRows(0);
        EntidadesDAO ert = new EntidadesDAO();
        for (Entidades c : ert.ler()) {
            modelo.addRow(new Object[]{
                c.getIdentidades(),
                c.getNome(),
                c.getHostilidade(),
                c.getDescriçao(),
                c.getTarefa(),
                c.getEngarregado()

            });

        }

    }

    public void setComboBox() {
        FuncionariosDAO ert = new FuncionariosDAO();
        pessoaBox.removeAllItems();
        for (Funcionarios r : ert.ler()) {
            pessoaBox.addItem(r.getNome());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nomeCampo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        hostilCampo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        desCampo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tarefCampo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        pessoaBox = new javax.swing.JComboBox<>();
        criarBotao = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tarefasTabela = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JButton();
        voltarBtn = new javax.swing.JButton();
        criarBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(857, 572));
        setMinimumSize(new java.awt.Dimension(857, 572));
        setPreferredSize(new java.awt.Dimension(857, 572));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 102));
        jLabel2.setText("CRIAR TRABALHO");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(230, 10, 250, 21);

        jLabel3.setForeground(new java.awt.Color(51, 255, 51));
        jLabel3.setText("Nome Da Entidade:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 50, 120, 16);
        getContentPane().add(nomeCampo);
        nomeCampo.setBounds(190, 50, 210, 22);

        jLabel4.setForeground(new java.awt.Color(102, 255, 102));
        jLabel4.setText("Hostilidade:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 80, 100, 20);
        getContentPane().add(hostilCampo);
        hostilCampo.setBounds(190, 80, 210, 22);

        jLabel5.setForeground(new java.awt.Color(102, 255, 102));
        jLabel5.setText("Descriçao:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 110, 100, 16);
        getContentPane().add(desCampo);
        desCampo.setBounds(190, 110, 210, 22);

        jLabel6.setForeground(new java.awt.Color(51, 255, 51));
        jLabel6.setText("Tarefa:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(100, 140, 90, 16);
        getContentPane().add(tarefCampo);
        tarefCampo.setBounds(190, 140, 210, 22);

        jLabel7.setForeground(new java.awt.Color(51, 255, 51));
        jLabel7.setText("Encarregado:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(90, 170, 90, 16);

        pessoaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pessoaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pessoaBoxActionPerformed(evt);
            }
        });
        getContentPane().add(pessoaBox);
        pessoaBox.setBounds(190, 170, 140, 22);

        criarBotao.setText("CRIAR");
        criarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarBotaoActionPerformed(evt);
            }
        });
        getContentPane().add(criarBotao);
        criarBotao.setBounds(440, 60, 170, 30);

        tarefasTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", " NOME", "HOSTILIDADE", "DESCRIÇAO", "TAREFA", "ENCARREGADO"
            }
        ));
        jScrollPane1.setViewportView(tarefasTabela);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 230, 860, 190);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(390, 100, 0, 0);

        deleteBtn.setText("DELETAR");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        getContentPane().add(deleteBtn);
        deleteBtn.setBounds(440, 120, 170, 30);

        voltarBtn.setText("voltar");
        voltarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(voltarBtn);
        voltarBtn.setBounds(621, 10, 110, 23);

        criarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/background.png"))); // NOI18N
        getContentPane().add(criarBtn);
        criarBtn.setBounds(0, -10, 880, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pessoaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pessoaBoxActionPerformed
        //lblCombo.setText((String) comboArea.getSelectItem());
    }//GEN-LAST:event_pessoaBoxActionPerformed

    private void voltarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarBtnActionPerformed
        TelaChefe y = new TelaChefe();//volta ao menu do chefe
        this.dispose();
        y.setVisible(true);
    }//GEN-LAST:event_voltarBtnActionPerformed

    private void criarBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarBotaoActionPerformed
        bean.setNome(nomeCampo.getText());//nome
        bean.setHostilidade(hostilCampo.getText());//hostilidade
        bean.setDescriçao(desCampo.getText());//descriçao
        bean.setTarefa(tarefCampo.getText());//tarefa
        bean.setEngarregado((String) pessoaBox.getSelectedItem());//encarregado

        dao.criar(bean);
        ReadJtable();
    }//GEN-LAST:event_criarBotaoActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        dao.Delete(bean);
        ReadJtable();
    }//GEN-LAST:event_deleteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTarefa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton criarBotao;
    private javax.swing.JLabel criarBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField desCampo;
    private javax.swing.JTextField hostilCampo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomeCampo;
    private javax.swing.JComboBox<String> pessoaBox;
    private javax.swing.JTextField tarefCampo;
    private javax.swing.JTable tarefasTabela;
    private javax.swing.JButton voltarBtn;
    // End of variables declaration//GEN-END:variables
}
