/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import model.bean.Entidades;
import model.dao.EntidadesDAO;
import model.bean.Funcionarios;

/**
 *
 * @author Senai
 */
public class TelaFuncionario extends javax.swing.JFrame {

    Entidades bean = new Entidades();
    EntidadesDAO dao = new EntidadesDAO();
  


    /**
     * Creates new form TelaFuncionario
     */
    public TelaFuncionario() {
        initComponents();
         addWindowListener(new WindowAdapter() {
            @Override
            public void windowOpened(WindowEvent e) {
              txtNome.setText(Funcionarios.getNomeAtual());
         }
        });
ReadJtable();
        trabalhoTabela.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent event) {
                if (!event.getValueIsAdjusting()) {
                    int linhaselecionada = trabalhoTabela.getSelectedRow();
                    if (linhaselecionada != -1) {
                        int IdAtual = (int) trabalhoTabela.getValueAt(linhaselecionada, 0);
                        bean.setIdentidades(IdAtual);
                    }
                }
            }

        });

    }

    public void ReadJtable() {
        DefaultTableModel modelo = (DefaultTableModel) trabalhoTabela.getModel();
        modelo.setNumRows(0);
        EntidadesDAO dao = new EntidadesDAO();
        for (Entidades c : dao.ler()) {
            modelo.addRow(new Object[]{
                c.getIdentidades(),
                c.getNome(),
                c.getHostilidade(),
                c.getDescriçao(),
                c.getTarefa(),
                c.getEngarregado()

            });

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        trabalhoTabela = new javax.swing.JTable();
        txtNome = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(861, 502));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 255, 51));
        jLabel2.setText("OLA FUNCIONARIO");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 60, 160, 50);

        jLabel3.setForeground(new java.awt.Color(102, 255, 102));
        jLabel3.setText("Estes sao os trabalhos que foram criados até agora,espere receber um trabalho");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 140, 510, 16);

        trabalhoTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOME", "HOSTILIDADE", "DESCRIÇAO", "TAREFA", "ENCARREGADO"
            }
        ));
        jScrollPane1.setViewportView(trabalhoTabela);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 180, 710, 270);

        txtNome.setForeground(new java.awt.Color(0, 204, 102));
        txtNome.setText("jLabel1");
        getContentPane().add(txtNome);
        txtNome.setBounds(220, 70, 90, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/background.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 860, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable trabalhoTabela;
    private javax.swing.JLabel txtNome;
    // End of variables declaration//GEN-END:variables
}
