/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import javax.swing.JOptionPane;
import model.bean.Entidades;
import model.bean.Funcionarios;
import model.dao.EntidadesDAO;
import model.dao.FuncionariosDAO;

/**
 *
 * @author User
 */
public class TelaLogin extends javax.swing.JFrame {

    Funcionarios bean = new Funcionarios();
    FuncionariosDAO dao = new FuncionariosDAO();
        Entidades beanE = new Entidades();
    EntidadesDAO daoE = new EntidadesDAO();

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usuarioCampo = new javax.swing.JTextField();
        Senha = new javax.swing.JLabel();
        senhaCampo = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(861, 502));
        setMinimumSize(new java.awt.Dimension(861, 502));
        setPreferredSize(new java.awt.Dimension(861, 502));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 51));
        jLabel1.setText("Login");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(250, 40, 178, 32);

        jLabel2.setForeground(new java.awt.Color(102, 255, 102));
        jLabel2.setText("Usuario");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 90, 80, 16);

        usuarioCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioCampoActionPerformed(evt);
            }
        });
        getContentPane().add(usuarioCampo);
        usuarioCampo.setBounds(180, 110, 224, 22);

        Senha.setForeground(new java.awt.Color(102, 255, 102));
        Senha.setText("Senha");
        getContentPane().add(Senha);
        Senha.setBounds(180, 140, 60, 16);
        getContentPane().add(senhaCampo);
        senhaCampo.setBounds(180, 160, 224, 22);

        loginBtn.setText("ENTRAR");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        getContentPane().add(loginBtn);
        loginBtn.setBounds(470, 130, 120, 23);

        jLabel5.setForeground(new java.awt.Color(0, 255, 0));
        jLabel5.setText("OLA,SEJA BEM VINDO AO B.I.L.U,UMA ORGANIZAÇAO GOVERNAMENTAL QUE CUIDA DE ENTIDADES ALIENIGINAS E SOBRENATURAIS");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 200, 810, 30);

        jLabel6.setForeground(new java.awt.Color(51, 255, 51));
        jLabel6.setText("COMO CHEFE,VC IRA CADASTRAR FUNCIONARIOS E CRIAR TAREFAS PARA ELES      ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(160, 210, 490, 70);

        jLabel4.setForeground(new java.awt.Color(102, 255, 102));
        jLabel4.setText("  COMO FUNCIONARIO VOCE TERA QUE FAZER O QUE FOR PEDIDO,NAO FAÇAM BESTEIRA");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(140, 270, 520, 16);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/background.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 860, 420);

        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(100, 40, 37, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        String usuario = usuarioCampo.getText();
        String senha = senhaCampo.getText();

        if (dao.lerLogin(usuario, senha)) {
            if (usuarioCampo.getText().equals("chefe") && new String(senhaCampo.getPassword()).equals("senha")) {
                JOptionPane.showMessageDialog(null, "login realizado com sucesso,bem vindo chefe");
                TelaChefe y = new TelaChefe();
                this.dispose();
                y.setVisible(true);

            } 
            else {
                
                JOptionPane.showMessageDialog(null, "login realizado com sucesso");
                TelaFuncionario u = new TelaFuncionario();
                this.dispose();
                u.setVisible(true);
            }
        }else{
                JOptionPane.showMessageDialog(null, "login errado");
                TelaLogin u = new TelaLogin();
                this.dispose();
                u.setVisible(false);
            }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void usuarioCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioCampoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Senha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField senhaCampo;
    private javax.swing.JTextField usuarioCampo;
    // End of variables declaration//GEN-END:variables
}
