/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import model.bean.Funcionarios;
import model.dao.FuncionariosDAO;

/**
 *
 * @author Senai
 */
public class TelaCadastro extends javax.swing.JFrame {

    Funcionarios bean = new Funcionarios();
    FuncionariosDAO dao = new FuncionariosDAO();

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
        ReadJtable();

        funciTabela.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent event) {
                if (!event.getValueIsAdjusting()) {
                    int linhaselecionada = funciTabela.getSelectedRow();
                    if (linhaselecionada != -1) {
                        int IdAtual = (int) funciTabela.getValueAt(linhaselecionada, 0);
                        bean.setIdfuncionarios(IdAtual);
                    }
                }
            }

        });

    }

    public void ReadJtable() {
        DefaultTableModel modelo = (DefaultTableModel) funciTabela.getModel();
        modelo.setNumRows(0);
        FuncionariosDAO ert = new FuncionariosDAO();//dao
        for (Funcionarios c : ert.ler()) {
            modelo.addRow(new Object[]{
                c.getIdfuncionarios(),
                c.getNome(),
                c.getCargo(),
                c.getIdade(),
                c.getCpf(),
                c.getDepartamento(),
                c.getUsuario(),
                c.getSenha()
             

            });

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomeCampo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cargoCampo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        deparCampo = new javax.swing.JTextField();
        criarCampo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        funciTabela = new javax.swing.JTable();
        idadeCampo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cpfCampo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        usuCampo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        senhaCampo = new javax.swing.JTextField();
        deleteCampo = new javax.swing.JButton();
        voltarBtn = new javax.swing.JButton();
        Editbtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(861, 502));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 51));
        jLabel1.setText("CADASTRAR");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 169, 32);

        jLabel2.setForeground(new java.awt.Color(51, 255, 51));
        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 50, 50, 16);
        getContentPane().add(nomeCampo);
        nomeCampo.setBounds(210, 50, 226, 22);

        jLabel3.setForeground(new java.awt.Color(51, 255, 51));
        jLabel3.setText("Cargo:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(140, 90, 50, 16);
        getContentPane().add(cargoCampo);
        cargoCampo.setBounds(210, 90, 226, 22);

        jLabel4.setForeground(new java.awt.Color(51, 255, 51));
        jLabel4.setText("Idade:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(140, 120, 40, 20);

        jLabel5.setForeground(new java.awt.Color(51, 255, 51));
        jLabel5.setText("Departamento:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(110, 190, 100, 16);
        getContentPane().add(deparCampo);
        deparCampo.setBounds(240, 190, 155, 22);

        criarCampo.setText("CRIAR");
        criarCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarCampoActionPerformed(evt);
            }
        });
        getContentPane().add(criarCampo);
        criarCampo.setBounds(510, 70, 107, 30);

        funciTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOME", "CARGO", "IDADE", "CPF", "DEPARTAMENTO", "USUARIO", "SENHA"
            }
        ));
        jScrollPane1.setViewportView(funciTabela);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 290, 860, 200);
        getContentPane().add(idadeCampo);
        idadeCampo.setBounds(290, 120, 53, 22);

        jLabel6.setForeground(new java.awt.Color(51, 255, 51));
        jLabel6.setText("CPF:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(140, 160, 40, 16);
        getContentPane().add(cpfCampo);
        cpfCampo.setBounds(240, 160, 156, 22);

        jLabel7.setForeground(new java.awt.Color(51, 255, 51));
        jLabel7.setText("Usuario:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(130, 220, 50, 16);
        getContentPane().add(usuCampo);
        usuCampo.setBounds(240, 220, 155, 22);

        jLabel8.setForeground(new java.awt.Color(102, 255, 102));
        jLabel8.setText("Senha:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(140, 250, 40, 16);
        getContentPane().add(senhaCampo);
        senhaCampo.setBounds(240, 250, 155, 22);

        deleteCampo.setText("DELETE");
        deleteCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCampoActionPerformed(evt);
            }
        });
        getContentPane().add(deleteCampo);
        deleteCampo.setBounds(510, 190, 107, 30);

        voltarBtn.setText("voltar");
        voltarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(voltarBtn);
        voltarBtn.setBounds(700, 10, 90, 23);

        Editbtn.setText("EDITAR");
        Editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Editbtn);
        Editbtn.setBounds(510, 130, 110, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/background.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, -10, 900, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarBtnActionPerformed
        TelaChefe y = new TelaChefe();//volta ao menu do chefe
        this.dispose();
        y.setVisible(true);
    }//GEN-LAST:event_voltarBtnActionPerformed

    private void criarCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarCampoActionPerformed
        bean.setNome(nomeCampo.getText());//nome
        bean.setCargo(cargoCampo.getText());//cargo
        bean.setIdade(idadeCampo.getText());///idade
        bean.setCpf(cpfCampo.getText());//cpf
        bean.setDepartamento(deparCampo.getText());//departamento
        bean.setUsuario(usuCampo.getText());//usuario
        bean.setSenha(senhaCampo.getText());//senha
        dao.criar(bean);
        ReadJtable();
    }//GEN-LAST:event_criarCampoActionPerformed

    private void deleteCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCampoActionPerformed
        dao.delete(bean);//delete
        ReadJtable();
    }//GEN-LAST:event_deleteCampoActionPerformed

    private void EditbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditbtnActionPerformed
        // TODO add your handling code here:
          bean.setNome(nomeCampo.getText());//nome
        bean.setCargo(cargoCampo.getText());//cargo
        bean.setIdade(idadeCampo.getText());///idade
        bean.setCpf(cpfCampo.getText());//cpf
        bean.setDepartamento(deparCampo.getText());//departamento
        bean.setUsuario(usuCampo.getText());//usuario
        bean.setSenha(senhaCampo.getText());//senha
       
        dao.update(bean);
        ReadJtable();
    }//GEN-LAST:event_EditbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Editbtn;
    private javax.swing.JTextField cargoCampo;
    private javax.swing.JTextField cpfCampo;
    private javax.swing.JButton criarCampo;
    private javax.swing.JButton deleteCampo;
    private javax.swing.JTextField deparCampo;
    private javax.swing.JTable funciTabela;
    private javax.swing.JTextField idadeCampo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomeCampo;
    private javax.swing.JTextField senhaCampo;
    private javax.swing.JTextField usuCampo;
    private javax.swing.JButton voltarBtn;
    // End of variables declaration//GEN-END:variables
}
